spring:
  application:
    name: MicroservizioBase
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Root
    url: jdbc:mysql://localhost:3306/videodb
    username: root
  jpa:
    hibernate:
      ddl-auto:
        update
      dialect:
        org.hibernate.dialect.MySQL8Dialect